# Generated by Django 5.0.6 on 2024-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetplan', '0003_category_cat_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
