# Generated by Django 5.0.2 on 2024-06-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetplan', '0004_activity_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-a_date'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
